### ISSUE TITLE
Spelling Mistakes In devops_maturity_framework

### ISSUE THREAD

**Issue by Abushawish** [adidas/adidas-devops-maturity-framework#10]
* **I'm submitting a ...**
  - [ ] bug report

* **What is the current behavior?**
- The crawl in "SRE role and activities" says 'responsibilty` 
- The walk in "Resiliency / Chaos Engineering" says 'resilency'
- The run in "Foster and enable team experimentation linked to business value" says 'experimentation'

* **What is the expected behavior?**
- The crawl in "SRE role and activities" should say 'responsibility` 
- The walk in "Resiliency / Chaos Engineering" should say 'resiliency'
- The run in "Foster and enable team experimentation linked to business value" should say 'experimentations' like crawl and walk do

* **What is the motivation / use case for changing the behavior?**
- Not a deal breaker, but spelling mistakes don't look professional 

* **Other information** (e.g. detailed explanation, related issues, links for us to have context, etc)
The spelling mistakes are in adidas-devops-maturity-framework/framework/devops_maturity_framework

Fix in my PR https://github.com/adidas/adidas-devops-maturity-framework/pull/11

**Comment by ialzorriz** [comment]
Thanks Abushawish for the corrections!
