### ISSUE TITLE
Possible typo

### ISSUE THREAD

**Issue by intltechventures** [adidas/adidas-devops-maturity-framework#2]
* **I'm submitting a ...**
  - [X ] bug report
  - [ ] feature request
  - [ ] support request
  

* **What is the current behavior?**
Possible typo in the devops_maturity_framework.md
"Tight" vs. "Tied"?
See Architecture Capability, "Use a loosely coupled architecture"

"System have no or very few direct dependencies to other systems. And those dependencies are tight to open standards and not tight to technologies and frameworks (e.g. Java RPC)"

* **What is the expected behavior?**
I assume "Tied" was intended?

* **What is the motivation / use case for changing the behavior?**
Help improve the quality of the documentation

* **Other information** (e.g. detailed explanation, related issues, links for us to have context, etc)
https://github.com/adidas/adidas-devops-maturity-framework/blob/master/framework/devops_maturity_framework.md

**Comment by ialzorriz** [comment]
Hi Kelvin, thanks for the heads up, typo fixed.
