### ISSUE TITLE
All production artifacts under version control

### ISSUE THREAD

**Issue by abitrolly** [adidas/adidas-devops-maturity-framework#3]
* **I'm submitting a ...**
  - [x] support request

* **What is the current behavior?**
You recommend that `All production artifacts under version control`. Does that mean you recommend to put binaries and docker containers into version control systems too?

* **What is the expected behavior?**
No binaries in `git`.

**Comment by ialzorriz** [comment]
Hi Anatoli,
When we talk of binaries and Docker images being under version control we mean that they are stored in artefact repository (nexus, artifactorty,..) or docker registries respectively. As you said no binaries should go in git :)

**Comment by abitrolly** [comment]
@ialzorriz then it is better to say that all production artifacts are versioned. [Version control](https://en.wikipedia.org/wiki/Version_control ) is a specific term that relates to software for managing source code.

**Comment by ialzorriz** [comment]
Hi @abitrolly 
You made a fair point. I've just updated that definition to make it more precise. 
Thanks for your input.
