### ISSUE TITLE
Platform Engineering provides base images

### ISSUE THREAD

**Issue by abitrolly** [adidas/adidas-devops-maturity-framework#4]
* **I'm submitting a ...**
  - [x] support request

* **What is the current behavior?**
What is Platform Engineering? Please clarify. If it is not the DevOps team then how are they different?

**Comment by ialzorriz** [comment]
Hi Anatoli,
In adidas we have a central platform that takes care of providing the teams with certain capabilities and platforms that they can use to build the applications on it. You can find more information in https://www.youtube.com/watch?v=XwaRKcjkAAo&t=469s
